baseURL = "http://shinmem.org/"
languageCode = "ru"
title = "ש\"מ | ShinMem"
theme = "chunky-poster"
copyright = "Copyright © 2010–2020, Daniel Levin."
googleAnalytics = "UA-4319585-4"

[params]
  author = "Daniel Levin"
  description = "אור השם"
  homepageImage = "/images/logo_shinmem_ship.jpg"
  share = true
